
name: PR debug
on:
  pull_request:
    branches:
     - master
jobs:
  pr_debug:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"