name: Integration tests

on:
    workflow_run:
        workflows: ['Test api', 'Test apa']
        types:
            - completed
jobs:
    it-tests:
        runs-on: ubuntu-latest
        needs: [build_api, build_apa]
        steps:
            - uses: actions/checkout@v2
