name: Pull Request
on: 
  push: 
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs: 
  correct_sha:
    runs-on: ubuntu-latest
    steps:
     - name: SHA bro
       run: |
        echo "${{github.sha}}"
        export GITHOOB=${{github.sha}}
        echo "${GITHOOB}"

  app: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
    env:
      GITHUB_ACTION_S3_BUCKET: sd.github-actions-artifact
      TERRAFORM_S3_BUCKET_KEY: terraform/${{github.repository}}/${{github.event_name}}/${{github.event.number}}
      TERRAFORM_ENVIRONMENT: ${{github.event_name}}_${{github.event.number}}"
    steps:
      - name: SHA bro
        run: |
          echo "${{github.sha}}"
          export GITHOOB=${{github.sha}}
          echo "${GITHOOB}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Ensure correct git hash dont cache me bro
        id: correct_git_hash
        run: echo ${{ github.sha }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Bash test
        env: 
          IMAGE_TAG: develop
        run: |
          if [ ${{ github.event_name == 'pull_request' }} ]; then export IMAGE_TAG=pull-request-${{github.event.number}}; fi
          echo $IMAGE_TAG
          echo ${{ github.sha }}
          git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS Credentials (SD Dev Account)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1
      - name: Terraform Init
        # if: github.event_name == 'pull_request' && github.event.action == 'open'
        run: |
          terraform init \
          -backend-config="bucket=$GITHUB_ACTION_S3_BUCKET" \
          -backend-config="key=$TERRAFORM_S3_BUCKET_KEY" \
          -backend-config="region=eu-west-1" \
          -var "aws_access_key=${{secrets.AWS_ACCESS_KEY}}" \
          -var "aws_secret_key=${{secrets.AWS_SECRET_KEY}}"
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        run: |
          terraform plan \
          -var "environment=${{github.event_name}}_${{github.event.number}}" \
          -var "aws_access_key=${{secrets.AWS_ACCESS_KEY}}" \
          -var "aws_secret_key=${{secrets.AWS_SECRET_KEY}}" \
          -out=plan.tfplan
      - name: Terraform Apply
        run: terraform apply  -auto-approve "plan.tfplan"
      - name: PR is closing - Terraform destroy
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          terraform destroy -auto-approve \
          -var "environment=${{github.event_name}}_${{github.event.number}}" \
          -var "aws_access_key=${{secrets.AWS_ACCESS_KEY}}" \
          -var "aws_secret_key=${{secrets.AWS_SECRET_KEY}}"

