name: Pull Request
on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs: 
  app: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: terraform
    steps: 
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS Credentials (SD Dev Account)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1
      - name: Terraform Init
        # if: github.event_name == 'pull_request' && github.event.action == 'open'
        run: |
          terraform init \
          -backend-config="bucket=sd.github-actions-artifact" \
          -backend-config="key=terraform/${{github.repository}}/${{github.event_name}}/${{github.event.number}}" \
          -backend-config="region=eu-west-1" \
          -var "aws_access_key=${{secrets.AWS_ACCESS_KEY}}" \
          -var "aws_secret_key=${{secrets.AWS_SECRET_KEY}}"
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Plan
        run: |
          terraform plan \
          -var "environment=${{github.event_name}}_${{github.event.number}}" \
          -var "aws_access_key=${{secrets.AWS_ACCESS_KEY}}" \
          -var "aws_secret_key=${{secrets.AWS_SECRET_KEY}}" \
          -out=plan.tfplan
      - name: Terraform Apply
        run: terraform apply  -auto-approve "plan.tfplan"
      - name: PR is closing - Terraform destroy
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          terraform destroy -auto-approve \
          -var "environment=${{github.event_name}}_${{github.event.number}}" \
          -var "aws_access_key=${{secrets.AWS_ACCESS_KEY}}" \
          -var "aws_secret_key=${{secrets.AWS_SECRET_KEY}}"

