name: Push
on: 
  push:
jobs:
  app: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash
        working-directory: terraform
    env:
      GITHUB_ACTION_S3_BUCKET: sd.github-actions-artifact
      TERRAFORM_S3_BUCKET_KEY: terraform/${{github.repository}}/${{github.event_name}}/${{github.event.number}}
      TERRAFORM_ENVIRONMENT: ${{github.event_name}}_${{github.event.number}}"
    steps: 
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Bash test
        run: docker version
      - name: Git Short
        run: |
          git rev-parse HEAD
          git rev-parse --short HEAD
          git log -10
          echo "hash = $(git rev-parse --short HEAD)"
          echo "::set-output name=sha7::$(git rev-parse --short HEAD)"
          jq .test ../test.json
