name: Deploy
on:
  push:
    branches: ["master"]
jobs:
  deploy_debug:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"